### ISSUE TITLE
Improve GrabCsv speed performance

### ISSUE THREAD

**Issue by sweatpantsdanny** [quintenrivers/Stockyard#14]
**Is your feature request related to a problem? Please describe.**
Pulling data from Yahoo takes too long for an array of assets to produce CSV files for. 

**Describe the solution you'd like**
Producing an array of CSV files should only take a couple seconds. 

**Describe alternatives you've considered**
1. Threading - Run multiple pull requests to Yahoo in parallel so several CSV files can be produced at one time.
2. Find a way to open only a specific part of the website. Opening only the part of the website responsible for showing the stock history will result in less wait time for the page to load and also less HTML for BeautifulSoup to parse through.

**Comment by sweatpantsdanny** [comment]
Multithread functionality has been implemented. Execution time to produce CSV files for 3 assets dropped from 16.75 seconds to 2.74 seconds

**Comment by quintenrivers** [comment]
Pushed data/get_data.py which can mine intraday and daily adjusted data
